version: '3.8'

services:
    postgres_pss_v2_db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: NOr8NUJSd3PtQHo
            POSTGRES_DB: pss_v2_db

    django_pss_v2_auth:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - postgres_pss_v2_db
volumes:
  postgres_data: